I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 22, in script call
    call semana2_dia4
  File "game/weeks/week_2/day_9.rpy", line 2, in script call
    call conversa_com_prolog_antes_aula
  File "game/weeks/week_2/day_9.rpy", line 15, in script
    mcN "Mais uma vez, você estava na sala de aula, um pouco entediado."
Exception: Sayer 'mcN' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 22, in script call
    call semana2_dia4
  File "game/weeks/week_2/day_9.rpy", line 2, in script call
    call conversa_com_prolog_antes_aula
  File "game/weeks/week_2/day_9.rpy", line 15, in script
    mcN "Mais uma vez, você estava na sala de aula, um pouco entediado."
  File "C:\Users\User\Desktop\renpy-8.1.2-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\User\Desktop\renpy-8.1.2-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'mcN' is not defined.

Windows-10-10.0.19041 AMD64
Ren'Py 8.1.2.23090503
ES_Weeks_Impl 1.0
Sun Oct 29 00:10:40 2023
